title: Caleb Ong Jun Yi # your name (or website title) here
logo: "/images/photoCircle.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  CFA | FRM | CAIA
  <br><br>
  Investment Data Analytics | Data Science | Financial Modelling | Wealth Management
  <br><br>
  Investment Analyst at PromiseLand Independent Financial Advisers Pte. Ltd.
  <br><br>
  <a href="https://www.linkedin.com/in/caleb-ong-frm-caia/">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-215708404-1 # your Google Analytics tracking ID here
