title: Caleb Ong Jun Yi # your name (or website title) here
logo: "/images/photoCircle.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  <br><br>
  Descriptive and Predictive Analytics for Investment Analysis and Risk Management
  <br><br>
  Assistant Manager, Investment Risk Management at Eastspring Investments
  <br><br>
  Connect with me at:
  <p><a href="mailto:calebongjunyi@gmail.com">Email: calebongjunyi@gmail.com </a></p>
  <a href="https://www.linkedin.com/in/caleb-ong-cfa-frm-caia/">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-215708404-1 # your Google Analytics tracking ID here
